/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_claydonkey_hidrd_FilePicker_ExtensionFilenameFilter */

#ifndef _Included_com_claydonkey_hidrd_FilePicker_ExtensionFilenameFilter
#define _Included_com_claydonkey_hidrd_FilePicker_ExtensionFilenameFilter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
